name: Docker CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  IMAGE_FILE: 'easy-notes-image.tar'
  REGISTRY_PATH: 'ghcr.io/hackerbukica666'
  IMAGE_NAME: 'easy-notes'
  IMAGE_VERSION: '1.0.4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and export Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: |
            ${{ env.REGISTRY_PATH }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
            ${{ env.REGISTRY_PATH }}/${{ env.IMAGE_NAME }}:latest
          outputs: type=docker,dest=${{ env.IMAGE_FILE }}

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: ${{ env.IMAGE_FILE }}
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image
        run: docker load < ${{ env.IMAGE_FILE }}

      - name: Create test network
        run: docker network create test-network

      - name: Start MySQL container
        run: |
          docker run -d --name mysql-test \
            --network test-network \
            -e MYSQL_ROOT_PASSWORD=root \
            -e MYSQL_DATABASE=easynotes \
            -e MYSQL_USER=easynotes \
            -e MYSQL_PASSWORD=easynotes \
            mysql:5.7

      - name: Wait for MySQL startup
        run: sleep 30 # Wartezeit auf 30 Sekunden erhöht

      - name: Initialize database
        run: docker exec -i mysql-test mysql -ueasynotes -peasynotes easynotes < dbseed.sql

      - name: Run application container
        run: |
          docker run -d --name easy-notes-test \
            --network test-network \
            -e DB_HOST=mysql-test \
            -e DB_PORT=3306 \
            -e DB_NAME=easynotes \
            -e DB_USER=easynotes \
            -e DB_PASS=easynotes \
            ${{ env.REGISTRY_PATH }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}

      - name: Verify application
        run: docker ps | grep easy-notes-test

      - name: Test application with curl
        run: |
          docker run --rm --network test-network alpine sh -c \
          "apk add --no-cache curl && curl -f http://easy-notes-test:8080/ || exit 1"

      - name: Cleanup
        run: |
          docker stop easy-notes-test mysql-test
          docker rm easy-notes-test mysql-test
          docker network rm test-network

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write # Berechtigungen für ghcr.io notwendig

    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image
        run: docker load < ${{ env.IMAGE_FILE }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ${{ env.REGISTRY_PATH }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
          docker tag ${{ env.REGISTRY_PATH }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} ${{ env.REGISTRY_PATH }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY_PATH }}/${{ env.IMAGE_NAME }}:latest
